//API TYPES-1.RESTFUL API(REPRESENTATIONAL STATE TRANSFER) 2.SOAP API(SIMPLE OBJECT ACCESS PROTOCOL)
//FETCH METHOD,HTTP METHODS, JSON(KEY-VALUE PAIR--LIKE OBJECT)-DATA FORMAT(DATA EXCHANGE,--CHANGING LANGUAGE/PARSING),API(WEB SERVICES)
//NOW USING FETCH METHOD-RETURNS PROMISES-ASYNCHRONOUS JS
fetch("https://fakestoreapi.com/Users")
.then((response)=>{
    console.log(response.json())//json()-to convert json into normal js objects(parsing)
})